### ISSUE TITLE
Dam hydra authorization error message is generic

### ISSUE THREAD

**Issue by monicavalluri** [GoogleCloudPlatform/healthcare-federated-access-services#36]
Scenario:
The access policy of the resource does not allow the user to get access. The current error message when the user tries to get access is `The authorization server encountered an unexpected condition that prevented it from fulfilling the request`.
It would be helpful if the error message says the exact issue with the login (Example: `Access policy requirements failed`).

dam-hydra logs:
```
time="2020-06-30T15:31:04Z" level=info msg="started handling request" method=PUT remote="127.0.0.1:43820" request="/oauth2/auth/requests/login/reject?login_challenge=178259991d29463fbde882d39fce0df1"
time="2020-06-30T15:31:05Z" level=info msg="completed handling request" measure#hydra/admin: https://data-access-manager.prod.dnastack.com/.latency=15268934 method=PUT remote="127.0.0.1:43820" request="/oauth2/auth/requests/login/reject?login_challenge=178259991d29463fbde882d39fce0df1" status=200 text_status=OK took=15.268934ms

level=error msg="An error occurred" debug="Failed to validate OpenID Connect request because session subject is empty." description="The authorization server encountered an unexpected condition that prevented it from fulfilling the request" error=server_error
```

**Comment by chaopeng** [comment]
The err `level=error msg="An error occurred" debug="Failed to validate OpenID Connect request because session subject is empty." description="The authorization server encountered an unexpected condition that prevented it from fulfilling the request" error=server_error` is from hydra, we found this issue last week when debugging with @mbarkley , it is becasuse in some case we dont pass the error to client. The fix is landed on repo. Will be in next release.

https://github.com/GoogleCloudPlatform/healthcare-federated-access-services/blob/9ac48a95474437893463c7d593dedb5b1353504d/lib/hydra/hydra_helper.go#L184

**Comment by mbarkley** [comment]
Thanks @chaopeng!
